# Generated by Django 4.1.1 on 2022-09-29 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicManager', '0002_city_dayweek_province_speciality_rating_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='addresses', to='medicManager.address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='specialties', to='medicManager.speciality'),
        ),
    ]
